### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by AlexanderRex** [FF-Projects-UE/UE_LibHaru#1]
Hello! Help me please with creating of pdf file.
I have install plugin, I am able to use blueprint nodes, I have set three nodes - create doc -add image -save doc, but nothing happens. I have set any desired parameter, but maybe I have make mistake (Print String after each node show me true)

**Comment by ffreality** [comment]
You didn't add page.
Think about it. You have your "PDF file object" but there is no page in it. So, image or text or any PDF object won't go anywhere.

https://blueprintue.com/blueprint/sgeiqxm4/
This is correct usage.

There are some unused functions, too. Like external fonts and u3d model import. I didn't delete them but also didn't use them.
(they works. I just don't have any external content)

**Comment by ffreality** [comment]
But I need to change image adding buffers It works but it can be better. (Only works with B8G8R8A8 PNGs)

**Comment by ffreality** [comment]
Okay, finished it. It should work with every compression settings.

Just be careful about alphas.
LibHaru uses RGB not RGBA or BGRA. So, you can't see transparent sides of your texture as transparent. Instead, I exposed an FColor for allowing you to define transparent color. For example if you set TransparentColor->R = 255, transparent sides will be red.

**Comment by AlexanderRex** [comment]
Thanks for so quickly answer! I will try it now!

**Comment by AlexanderRex** [comment]
It works amazing, thank you guys!

**Comment by AlexanderRex** [comment]
Thank you for your help! May I ask you: I want to create a linkedin post
about your plugin, and attach there link to your GitHub and linked in
maybe, can you provide it?
I think your plugin is very helpful and useful, lets help more developers
know about it. If you are agree

чт, 6 июл. 2023 г. в 11:34, Frozen Forest Reality Technologies <
***@***.***>:

**Comment by ffreality** [comment]
Of course !
https://www.linkedin.com/company/ffreality/

Actually we will be happy if there are some exprienced pdfium developers. Our other plugin supports android, reading, rendering and writing. But its functions are really makes no sense and there is literally no documentation.

When we try to add relatively big images, pdf "files" come broken even if PDF objects are correct. PDFium user group said about loop saving of blocks but I couldn't understand it.

So if anyone helps me, I all there pdf processes can be done with single plugin and I can eve  pay for it.

**Comment by AlexanderRex** [comment]
Yeah, I have checked big texture resolution and its same problem with that, just black image
